#!/usr/bin/env php
<?php

const VERSION = '0.0.1';
require __DIR__ . '/vendor/autoload.php';

use Tworzenieweb\SqlProvisioner\Application;

$application = new Application();
$application->setName('SQL Provisioner');
$application->setVersion(VERSION);
$application->run();